### ISSUE TITLE
How to access the text as string from detection

### ISSUE THREAD

**Issue by azamsharp** [hollisliu/iOS-Vision-Text-Detection-Demo#2]
How do you access the actual text that is detected? 

Have you tried detecting numbers because it only seems to work on alphabets?

**Comment by hollisliu** [comment]
There is no way of getting text value using the Vision framework at this point. As I stated in README: "There is no OCR framework in the iOS SDK still. As a result a seperate OCR engine is needed to recognize detected text content."

**Comment by jppgks** [comment]
@hollisliu Do you have experience with any OCR engines for iOS? Which one do you recommend? Cheers!

**Comment by hollisliu** [comment]
Tesseract OCR is a good choice!
