### ISSUE TITLE
iPad Display Issues

### ISSUE THREAD

**Issue by yeldarby** [hollisliu/iOS-Vision-Text-Detection-Demo#3]
On iPad the camera frame doesn't take up the whole screen and bounding boxes are misaligned.

![img_0052](https://user-images.githubusercontent.com/870796/27997974-0ae29336-64c9-11e7-8e61-cecd58bb0648.PNG)

**Comment by yeldarby** [comment]
Modifying `Preview View`'s constraints in `Main.storyboard` and adding `previewLayer.videoGravity = AVLayerVideoGravity.resize;` in `VNTextViewController.swift` seems to have fixed the display and alignment issues.

**Comment by khurram18** [comment]
Solved and create a pull request for this, please see pull request [here](https://github.com/hollisliu/iOS-Vision-Text-Detection-Demo/pull/4)

**Comment by hollisliu** [comment]
This bug should be fixed now
